// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgsPo3SFwuMjYy1LtuDaz8diYIVbqXu_A',
    appId: '1:444171514459:web:5b89b269bc4c4f09f1c57e',
    messagingSenderId: '444171514459',
    projectId: 'login-and-register-app-4c6bd',
    authDomain: 'login-and-register-app-4c6bd.firebaseapp.com',
    storageBucket: 'login-and-register-app-4c6bd.firebasestorage.app',
    measurementId: 'G-6LB9TBR1KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBXajQHPfMsSoD1ONXj-AeAtxhsjU_Vs',
    appId: '1:444171514459:android:4d459df208175762f1c57e',
    messagingSenderId: '444171514459',
    projectId: 'login-and-register-app-4c6bd',
    storageBucket: 'login-and-register-app-4c6bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADEQGMiLGVITbxw5KcT_oyJCBpoVNHjBE',
    appId: '1:444171514459:ios:cec4b6e8205492d9f1c57e',
    messagingSenderId: '444171514459',
    projectId: 'login-and-register-app-4c6bd',
    storageBucket: 'login-and-register-app-4c6bd.firebasestorage.app',
    iosBundleId: 'com.example.loginAndRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADEQGMiLGVITbxw5KcT_oyJCBpoVNHjBE',
    appId: '1:444171514459:ios:cec4b6e8205492d9f1c57e',
    messagingSenderId: '444171514459',
    projectId: 'login-and-register-app-4c6bd',
    storageBucket: 'login-and-register-app-4c6bd.firebasestorage.app',
    iosBundleId: 'com.example.loginAndRegisterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgsPo3SFwuMjYy1LtuDaz8diYIVbqXu_A',
    appId: '1:444171514459:web:b21ab29c9200fefbf1c57e',
    messagingSenderId: '444171514459',
    projectId: 'login-and-register-app-4c6bd',
    authDomain: 'login-and-register-app-4c6bd.firebaseapp.com',
    storageBucket: 'login-and-register-app-4c6bd.firebasestorage.app',
    measurementId: 'G-T18BP4VY4P',
  );

}